export const actions = {
    loadingPage: 'LOADINGPAGE',
    CHANGE_CHECKING: 'CHANGE_CHECKING',
    CHANGE_CHECKOUT: 'CHANGE_CHECKOUT',
    CHANGE_PAGES: 'CHANGE_PAGES',
    REQUEST_PROJECTS: 'REQUEST_PROJECTS',
    RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
    CHANGE_PROJECT_SELECTED: 'CHANGE_PROJECT_SELECTED',
    LOADING_COMPONENTS: 'LOADING_COMPONENTS',
    LOADED_COMPONENTS: 'LOADED_COMPONENT',
    LOADING_DEVICES: 'LOADING_DEVICES',
    LOADED_DEVICES: 'LOADED_DEVICES',
    LOADING_DEVICES_PAGES: 'LOADING_DEVICES_PAGES',
    LOADED_DEVICES_PAGES: 'LOADED_DEVICES_PAGES',

    ANALYTICS_IS_FETCHING: 'ANALYTICS_IS_FETCHING',
    ANALYTICS_IS_FETCHING_DONE: 'ANALYTICS_IS_FETCHING_DONE',
    ANALYTICS_REPORT_DATA: 'ANALYTICS_REPORT_DATA',
    ANALYTICS_CREATING_REPORT: 'ANALYTICS_CREATING_REPORT',
    ANALYTICS_CREATED_REPORT: 'ANALYTICS_CREATED_REPORT',
    ANALYTICS_RETREIVED_REPORTS: 'ANALYTICS_RETREIVED_REPORTS',
    ANALYTICS_RETRIEVING_REPORTS: 'ANALYTICS_RETRIEVING_REPORTS',
    ANALYTICS_LOAD_REPORTS: 'ANALYTICS_LOAD_REPORTS'
};
