export const actions = {
    loadingPage: 'LOADINGPAGE',
    CHANGE_CHECKING: 'CHANGE_CHECKING',
    CHANGE_CHECKOUT: 'CHANGE_CHECKOUT',
    CHANGE_PAGES: 'CHANGE_PAGES',
    REQUEST_PROJECTS: 'REQUEST_PROJECTS',
    RECEIVE_PROJECTS: 'RECEIVE_PROJECTS',
    CHANGE_PROJECT: 'CHANGEPROJECT'
};
